/**
 * @file modules/biolink/templates/presets/bold.ts
 * @module biolink
 * @description Templates de la catégorie "Audacieux".
 *   Couleurs vives, contrastes forts, typographies imposantes.
 */

import type { BioTemplate } from '../types'

/** 8 templates audacieux (7 classic + 1 hero) */
export const BOLD_TEMPLATES: BioTemplate[] = [
  {
    id: 'electric-coral',
    name: 'Corail électrique',
    category: 'bold',
    tags: ['rose', 'orange', 'vif', 'gradient'],
    theme: 'gradient',
    accentColor: '#f43f5e',
    titleColor: '#ffffff',
    bioColor: '#fecdd3',
    linkColor: '#ffffff',
    fontFamily: 'poppins',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#f43f5e',
    gradientTo: '#f97316',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'royal-purple',
    name: 'Violet royal',
    category: 'bold',
    tags: ['violet', 'bleu', 'royal', 'imposant'],
    theme: 'gradient',
    accentColor: '#8b5cf6',
    titleColor: '#ffffff',
    bioColor: '#ddd6fe',
    linkColor: '#ffffff',
    fontFamily: 'bebas-neue',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: '#7c3aed',
    gradientTo: '#2563eb',
    linkSpacing: 'compact',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'sunset-blaze',
    name: 'Flamme couchante',
    category: 'bold',
    tags: ['orange', 'rouge', 'chaud', 'feu'],
    theme: 'gradient',
    accentColor: '#ea580c',
    titleColor: '#ffffff',
    bioColor: '#fed7aa',
    linkColor: '#ffffff',
    fontFamily: 'poppins',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: '#dc2626',
    gradientTo: '#f59e0b',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'hot-pink',
    name: 'Rose flash',
    category: 'bold',
    tags: ['rose', 'fuchsia', 'vif', 'pop'],
    theme: 'default',
    accentColor: '#ec4899',
    titleColor: '#831843',
    bioColor: '#be185d',
    linkColor: '#ffffff',
    fontFamily: 'poppins',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'thunder-bolt',
    name: 'Coup de tonnerre',
    category: 'bold',
    tags: ['jaune', 'noir', 'contraste', 'puissant'],
    theme: 'dark',
    accentColor: '#eab308',
    titleColor: '#fef08a',
    bioColor: '#facc15',
    linkColor: '#18181b',
    fontFamily: 'bebas-neue',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'compact',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'ocean-wave',
    name: 'Vague océan',
    category: 'bold',
    tags: ['bleu', 'cyan', 'profond', 'marin'],
    theme: 'gradient',
    accentColor: '#0ea5e9',
    titleColor: '#ffffff',
    bioColor: '#bae6fd',
    linkColor: '#ffffff',
    fontFamily: 'dm-sans',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#0369a1',
    gradientTo: '#06b6d4',
    linkSpacing: 'normal',
    hoverAnimation: 'slide',
    headerStyle: 'classic',
  },
  {
    id: 'crimson-fury',
    name: 'Fureur cramoisie',
    category: 'bold',
    tags: ['rouge', 'sombre', 'intense', 'passion'],
    theme: 'dark',
    accentColor: '#ef4444',
    titleColor: '#fca5a5',
    bioColor: '#fca5a5',
    linkColor: '#ffffff',
    fontFamily: 'bebas-neue',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  // ── Template Hero ───────────────────────────────────────────────────────
  {
    id: 'sunset-hero',
    name: 'Coucher de soleil hero',
    category: 'bold',
    tags: ['rouge', 'orange', 'hero', 'gradient', 'coucher-de-soleil'],
    theme: 'gradient',
    accentColor: '#ea580c',
    titleColor: '#ffffff',
    bioColor: '#fed7aa',
    linkColor: '#ffffff',
    fontFamily: 'bebas-neue',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#dc2626',
    gradientTo: '#f97316',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'hero',
  },
]
