/**
 * @file modules/biolink/templates/presets/creative.ts
 * @module biolink
 * @description Templates de la catégorie "Créatif".
 *   Designs artistiques, expressifs, contrastes forts et choix audacieux.
 */

import type { BioTemplate } from '../types'

/** 8 templates créatifs (7 classic + 1 banner) */
export const CREATIVE_TEMPLATES: BioTemplate[] = [
  {
    id: 'ink-splash',
    name: 'Éclaboussure d\'encre',
    category: 'creative',
    tags: ['noir', 'contraste', 'encre', 'art'],
    theme: 'default',
    accentColor: '#18181b',
    titleColor: '#18181b',
    bioColor: '#3f3f46',
    linkColor: '#ffffff',
    fontFamily: 'bebas-neue',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'compact',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'neon-canvas',
    name: 'Toile néon',
    category: 'creative',
    tags: ['néon', 'multicolore', 'art', 'vif'],
    theme: 'neon',
    accentColor: '#f43f5e',
    titleColor: '#fb7185',
    bioColor: '#fda4af',
    linkColor: '#ffffff',
    fontFamily: 'poppins',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'paper-fold',
    name: 'Papier plié',
    category: 'creative',
    tags: ['blanc', 'ombre', 'origami', 'minimal'],
    theme: 'minimal',
    accentColor: '#6b7280',
    titleColor: '#1f2937',
    bioColor: '#6b7280',
    linkColor: '#1f2937',
    fontFamily: 'inter',
    buttonShape: 'rounded-lg',
    buttonVariant: 'shadow',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'airy',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'abstract-art',
    name: 'Art abstrait',
    category: 'creative',
    tags: ['violet', 'orange', 'abstrait', 'moderne'],
    theme: 'gradient',
    accentColor: '#a855f7',
    titleColor: '#ffffff',
    bioColor: '#e9d5ff',
    linkColor: '#ffffff',
    fontFamily: 'outfit',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#a855f7',
    gradientTo: '#f97316',
    linkSpacing: 'normal',
    hoverAnimation: 'slide',
    headerStyle: 'classic',
  },
  {
    id: 'pop-art',
    name: 'Pop art',
    category: 'creative',
    tags: ['jaune', 'rouge', 'pop', 'comic'],
    theme: 'default',
    accentColor: '#dc2626',
    titleColor: '#1e3a8a',
    bioColor: '#dc2626',
    linkColor: '#ffffff',
    fontFamily: 'bebas-neue',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: '#fef08a',
    gradientTo: '#fef9c3',
    linkSpacing: 'compact',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'watercolor',
    name: 'Aquarelle',
    category: 'creative',
    tags: ['bleu', 'rose', 'aquarelle', 'doux'],
    theme: 'default',
    accentColor: '#7c3aed',
    titleColor: '#4c1d95',
    bioColor: '#6d28d9',
    linkColor: '#ffffff',
    fontFamily: 'playfair',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#dbeafe',
    gradientTo: '#fce7f3',
    linkSpacing: 'airy',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'graffiti',
    name: 'Graffiti',
    category: 'creative',
    tags: ['néon', 'urbain', 'street', 'art'],
    theme: 'dark',
    accentColor: '#22c55e',
    titleColor: '#4ade80',
    bioColor: '#86efac',
    linkColor: '#ffffff',
    fontFamily: 'bebas-neue',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: '#18181b',
    gradientTo: '#1e1b4b',
    linkSpacing: 'compact',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  // ── Template Banner ─────────────────────────────────────────────────────
  {
    id: 'gallery-banner',
    name: 'Galerie bannière',
    category: 'creative',
    tags: ['bannière', 'galerie', 'carte', 'flottante', 'artistique'],
    theme: 'default',
    accentColor: '#7c3aed',
    titleColor: '#1e1b4b',
    bioColor: '#6b7280',
    linkColor: null,
    fontFamily: 'playfair',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: '#ede9fe',
    gradientTo: '#fae8ff',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'banner',
  },
]
