/**
 * @file modules/biolink/templates/presets/dark.ts
 * @module biolink
 * @description Templates de la catégorie "Sombre".
 *   Thèmes sombres, élégants, avec des accents lumineux sur fond noir.
 */

import type { BioTemplate } from '../types'

/** 8 templates sombres (7 classic + 1 hero) */
export const DARK_TEMPLATES: BioTemplate[] = [
  {
    id: 'midnight-black',
    name: 'Noir de minuit',
    category: 'dark',
    tags: ['noir', 'violet', 'élégant', 'nuit'],
    theme: 'dark',
    accentColor: '#8b5cf6',
    titleColor: '#e9d5ff',
    bioColor: '#c4b5fd',
    linkColor: '#ffffff',
    fontFamily: 'inter',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'cyber-punk',
    name: 'Cyberpunk',
    category: 'dark',
    tags: ['néon', 'cyan', 'futuriste', 'tech'],
    theme: 'neon',
    accentColor: '#06b6d4',
    titleColor: '#22d3ee',
    bioColor: '#67e8f9',
    linkColor: '#ffffff',
    fontFamily: 'space-grotesk',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'compact',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'aurora-dark',
    name: 'Aurore sombre',
    category: 'dark',
    tags: ['vert', 'violet', 'aurore', 'boréale'],
    theme: 'dark',
    accentColor: '#10b981',
    titleColor: '#a7f3d0',
    bioColor: '#6ee7b7',
    linkColor: '#ffffff',
    fontFamily: 'dm-sans',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#059669',
    gradientTo: '#7c3aed',
    linkSpacing: 'normal',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'obsidian',
    name: 'Obsidienne',
    category: 'dark',
    tags: ['noir', 'gris', 'minimal', 'sombre'],
    theme: 'dark',
    accentColor: '#a1a1aa',
    titleColor: '#e4e4e7',
    bioColor: '#a1a1aa',
    linkColor: '#ffffff',
    fontFamily: 'inter',
    buttonShape: 'rounded-lg',
    buttonVariant: 'outline',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'dark-rose',
    name: 'Rose sombre',
    category: 'dark',
    tags: ['rose', 'noir', 'romantique', 'sombre'],
    theme: 'dark',
    accentColor: '#f43f5e',
    titleColor: '#fda4af',
    bioColor: '#fb7185',
    linkColor: '#ffffff',
    fontFamily: 'playfair',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'airy',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'deep-ocean',
    name: 'Océan profond',
    category: 'dark',
    tags: ['bleu', 'profond', 'abyssal', 'mer'],
    theme: 'dark',
    accentColor: '#3b82f6',
    titleColor: '#93c5fd',
    bioColor: '#60a5fa',
    linkColor: '#ffffff',
    fontFamily: 'dm-sans',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#1e3a5f',
    gradientTo: '#0f172a',
    linkSpacing: 'normal',
    hoverAnimation: 'slide',
    headerStyle: 'classic',
  },
  {
    id: 'shadow-gold',
    name: 'Or ombré',
    category: 'dark',
    tags: ['or', 'noir', 'doré', 'chic'],
    theme: 'dark',
    accentColor: '#d97706',
    titleColor: '#fcd34d',
    bioColor: '#fbbf24',
    linkColor: '#18181b',
    fontFamily: 'playfair',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  // ── Template Hero ───────────────────────────────────────────────────────
  {
    id: 'midnight-hero',
    name: 'Minuit hero',
    category: 'dark',
    tags: ['sombre', 'violet', 'hero', 'gradient', 'nuit'],
    theme: 'dark',
    accentColor: '#8b5cf6',
    titleColor: '#ffffff',
    bioColor: '#c4b5fd',
    linkColor: '#ffffff',
    fontFamily: 'inter',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#1e1b4b',
    gradientTo: '#312e81',
    linkSpacing: 'normal',
    hoverAnimation: 'glow',
    headerStyle: 'hero',
  },
]
