/**
 * @file modules/biolink/templates/presets/fashion.ts
 * @module biolink
 * @description Templates de la catégorie "Mode".
 *   Haute couture, streetwear, tendances et élégance vestimentaire.
 */

import type { BioTemplate } from '../types'

/** 8 templates mode (7 classic + 1 banner) */
export const FASHION_TEMPLATES: BioTemplate[] = [
  {
    id: 'haute-couture',
    name: 'Haute couture',
    category: 'fashion',
    tags: ['noir', 'sérif', 'élégant', 'luxe'],
    theme: 'dark',
    accentColor: '#e5e7eb',
    titleColor: '#f9fafb',
    bioColor: '#d1d5db',
    linkColor: '#18181b',
    fontFamily: 'playfair',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'airy',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'streetwear',
    name: 'Streetwear',
    category: 'fashion',
    tags: ['bold', 'urbain', 'street', 'moderne'],
    theme: 'dark',
    accentColor: '#f97316',
    titleColor: '#fdba74',
    bioColor: '#fb923c',
    linkColor: '#ffffff',
    fontFamily: 'bebas-neue',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'compact',
    hoverAnimation: 'slide',
    headerStyle: 'classic',
  },
  {
    id: 'pastel-chic',
    name: 'Pastel chic',
    category: 'fashion',
    tags: ['rose', 'poudré', 'chic', 'féminin'],
    theme: 'default',
    accentColor: '#f9a8d4',
    titleColor: '#831843',
    bioColor: '#9d174d',
    linkColor: '#831843',
    fontFamily: 'playfair',
    buttonShape: 'rounded-lg',
    buttonVariant: 'outline',
    avatarShape: 'circle',
    gradientFrom: '#fdf2f8',
    gradientTo: '#fff1f2',
    linkSpacing: 'airy',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'monochrome-style',
    name: 'Monochrome stylé',
    category: 'fashion',
    tags: ['noir', 'blanc', 'contraste', 'classe'],
    theme: 'default',
    accentColor: '#18181b',
    titleColor: '#18181b',
    bioColor: '#52525b',
    linkColor: '#ffffff',
    fontFamily: 'outfit',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'vintage-fashion',
    name: 'Vintage mode',
    category: 'fashion',
    tags: ['sépia', 'vintage', 'rétro', 'classique'],
    theme: 'minimal',
    accentColor: '#a16207',
    titleColor: '#451a03',
    bioColor: '#78350f',
    linkColor: '#451a03',
    fontFamily: 'playfair',
    buttonShape: 'rounded-lg',
    buttonVariant: 'outline',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'airy',
    hoverAnimation: 'none',
    headerStyle: 'classic',
  },
  {
    id: 'neon-runway',
    name: 'Défilé néon',
    category: 'fashion',
    tags: ['néon', 'rose', 'défilé', 'flashy'],
    theme: 'neon',
    accentColor: '#e879f9',
    titleColor: '#f0abfc',
    bioColor: '#d946ef',
    linkColor: '#ffffff',
    fontFamily: 'poppins',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'editorial',
    name: 'Éditorial',
    category: 'fashion',
    tags: ['beige', 'sérif', 'magazine', 'presse'],
    theme: 'minimal',
    accentColor: '#78716c',
    titleColor: '#1c1917',
    bioColor: '#57534e',
    linkColor: '#1c1917',
    fontFamily: 'lora',
    buttonShape: 'rounded-lg',
    buttonVariant: 'outline',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'airy',
    hoverAnimation: 'none',
    headerStyle: 'classic',
  },
  // ── Template Banner ─────────────────────────────────────────────────────
  {
    id: 'editorial-banner',
    name: 'Éditorial bannière',
    category: 'fashion',
    tags: ['bannière', 'éditorial', 'élégant', 'carte', 'sérif'],
    theme: 'minimal',
    accentColor: '#44403c',
    titleColor: '#1c1917',
    bioColor: '#78716c',
    linkColor: '#1c1917',
    fontFamily: 'playfair',
    buttonShape: 'rounded-lg',
    buttonVariant: 'outline',
    avatarShape: 'rounded-square',
    gradientFrom: '#fafaf9',
    gradientTo: '#f5f5f4',
    linkSpacing: 'airy',
    hoverAnimation: 'scale',
    headerStyle: 'banner',
  },
]
