/**
 * @file modules/biolink/templates/presets/food.ts
 * @module biolink
 * @description Templates de la catégorie "Food".
 *   Cuisine, gastronomie, couleurs chaudes et organiques.
 */

import type { BioTemplate } from '../types'

/** 7 templates food */
export const FOOD_TEMPLATES: BioTemplate[] = [
  {
    id: 'terracotta',
    name: 'Terre cuite',
    category: 'food',
    tags: ['terre', 'cuite', 'marron', 'rustique'],
    theme: 'default',
    accentColor: '#b45309',
    titleColor: '#78350f',
    bioColor: '#92400e',
    linkColor: '#ffffff',
    fontFamily: 'lora',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'fresh-garden',
    name: 'Jardin frais',
    category: 'food',
    tags: ['vert', 'frais', 'bio', 'organique'],
    theme: 'default',
    accentColor: '#16a34a',
    titleColor: '#14532d',
    bioColor: '#166534',
    linkColor: '#ffffff',
    fontFamily: 'dm-sans',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#f0fdf4',
    gradientTo: '#ecfdf5',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'coffee-shop',
    name: 'Café',
    category: 'food',
    tags: ['brun', 'café', 'chaud', 'cosy'],
    theme: 'default',
    accentColor: '#92400e',
    titleColor: '#451a03',
    bioColor: '#78350f',
    linkColor: '#ffffff',
    fontFamily: 'lora',
    buttonShape: 'rounded-lg',
    buttonVariant: 'shadow',
    avatarShape: 'circle',
    gradientFrom: '#fef3c7',
    gradientTo: '#fffbeb',
    linkSpacing: 'airy',
    hoverAnimation: 'none',
    headerStyle: 'classic',
  },
  {
    id: 'fresh-citrus',
    name: 'Agrumes frais',
    category: 'food',
    tags: ['orange', 'citron', 'frais', 'été'],
    theme: 'default',
    accentColor: '#ea580c',
    titleColor: '#7c2d12',
    bioColor: '#c2410c',
    linkColor: '#ffffff',
    fontFamily: 'poppins',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#fff7ed',
    gradientTo: '#fffbeb',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'bakery',
    name: 'Boulangerie',
    category: 'food',
    tags: ['beige', 'pain', 'doux', 'artisanal'],
    theme: 'minimal',
    accentColor: '#a16207',
    titleColor: '#713f12',
    bioColor: '#854d0e',
    linkColor: '#713f12',
    fontFamily: 'playfair',
    buttonShape: 'rounded-lg',
    buttonVariant: 'outline',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'airy',
    hoverAnimation: 'none',
    headerStyle: 'classic',
  },
  {
    id: 'sushi-bar',
    name: 'Sushi bar',
    category: 'food',
    tags: ['rouge', 'noir', 'japonais', 'asiatique'],
    theme: 'dark',
    accentColor: '#dc2626',
    titleColor: '#fca5a5',
    bioColor: '#f87171',
    linkColor: '#ffffff',
    fontFamily: 'dm-sans',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'tropical-smoothie',
    name: 'Smoothie tropical',
    category: 'food',
    tags: ['rose', 'vert', 'tropical', 'fruité'],
    theme: 'default',
    accentColor: '#ec4899',
    titleColor: '#831843',
    bioColor: '#9d174d',
    linkColor: '#ffffff',
    fontFamily: 'poppins',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#fce7f3',
    gradientTo: '#d1fae5',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
]
