/**
 * @file modules/biolink/templates/presets/gaming.ts
 * @module biolink
 * @description Templates de la catégorie "Gaming".
 *   Univers gaming, esport, couleurs néon et typographies impactantes.
 */

import type { BioTemplate } from '../types'

/** 7 templates gaming */
export const GAMING_TEMPLATES: BioTemplate[] = [
  {
    id: 'rgb-gamer',
    name: 'RGB Gamer',
    category: 'gaming',
    tags: ['rouge', 'néon', 'gamer', 'rgb'],
    theme: 'dark',
    accentColor: '#ef4444',
    titleColor: '#fca5a5',
    bioColor: '#f87171',
    linkColor: '#ffffff',
    fontFamily: 'bebas-neue',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'compact',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'twitch-purple',
    name: 'Twitch violet',
    category: 'gaming',
    tags: ['violet', 'twitch', 'stream', 'live'],
    theme: 'dark',
    accentColor: '#9146ff',
    titleColor: '#c4b5fd',
    bioColor: '#a78bfa',
    linkColor: '#ffffff',
    fontFamily: 'poppins',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'toxic-green',
    name: 'Vert toxique',
    category: 'gaming',
    tags: ['vert', 'toxique', 'acide', 'néon'],
    theme: 'dark',
    accentColor: '#84cc16',
    titleColor: '#bef264',
    bioColor: '#a3e635',
    linkColor: '#1a2e05',
    fontFamily: 'bebas-neue',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'compact',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'cyber-racer',
    name: 'Cyber racer',
    category: 'gaming',
    tags: ['cyan', 'course', 'vitesse', 'futuriste'],
    theme: 'neon',
    accentColor: '#06b6d4',
    titleColor: '#22d3ee',
    bioColor: '#67e8f9',
    linkColor: '#ffffff',
    fontFamily: 'bebas-neue',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: '#0e7490',
    gradientTo: '#18181b',
    linkSpacing: 'compact',
    hoverAnimation: 'slide',
    headerStyle: 'classic',
  },
  {
    id: 'dark-souls',
    name: 'Âmes sombres',
    category: 'gaming',
    tags: ['sombre', 'rouge', 'épique', 'rpg'],
    theme: 'dark',
    accentColor: '#b91c1c',
    titleColor: '#fca5a5',
    bioColor: '#f87171',
    linkColor: '#ffffff',
    fontFamily: 'playfair',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#1c1917',
    gradientTo: '#0c0a09',
    linkSpacing: 'normal',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'pixel-retro-game',
    name: 'Pixel rétro',
    category: 'gaming',
    tags: ['pixel', 'rétro', '8bit', 'arcade'],
    theme: 'dark',
    accentColor: '#facc15',
    titleColor: '#fef08a',
    bioColor: '#fde047',
    linkColor: '#422006',
    fontFamily: 'space-grotesk',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'compact',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'esport-pro',
    name: 'Esport pro',
    category: 'gaming',
    tags: ['bleu', 'esport', 'pro', 'compétitif'],
    theme: 'dark',
    accentColor: '#2563eb',
    titleColor: '#93c5fd',
    bioColor: '#60a5fa',
    linkColor: '#ffffff',
    fontFamily: 'dm-sans',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: '#1e3a5f',
    gradientTo: '#0f172a',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
]
