/**
 * @file modules/biolink/templates/presets/gradient.ts
 * @module biolink
 * @description Templates de la catégorie "Dégradé".
 *   Fonds dégradés colorés, vibrants et immersifs.
 */

import type { BioTemplate } from '../types'

/** 8 templates dégradé (7 classic + 1 card) */
export const GRADIENT_TEMPLATES: BioTemplate[] = [
  {
    id: 'aurora-borealis',
    name: 'Aurore boréale',
    category: 'gradient',
    tags: ['cyan', 'violet', 'aurore', 'nordique'],
    theme: 'gradient',
    accentColor: '#06b6d4',
    titleColor: '#ffffff',
    bioColor: '#cffafe',
    linkColor: '#ffffff',
    fontFamily: 'dm-sans',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#06b6d4',
    gradientTo: '#8b5cf6',
    linkSpacing: 'normal',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'sunset-vibes',
    name: 'Vibes coucher de soleil',
    category: 'gradient',
    tags: ['orange', 'rose', 'coucher', 'chaud'],
    theme: 'gradient',
    accentColor: '#f97316',
    titleColor: '#ffffff',
    bioColor: '#fed7aa',
    linkColor: '#ffffff',
    fontFamily: 'poppins',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#f97316',
    gradientTo: '#ec4899',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'northern-lights',
    name: 'Lumières du nord',
    category: 'gradient',
    tags: ['vert', 'bleu', 'boréal', 'magique'],
    theme: 'gradient',
    accentColor: '#10b981',
    titleColor: '#ffffff',
    bioColor: '#a7f3d0',
    linkColor: '#ffffff',
    fontFamily: 'inter',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#10b981',
    gradientTo: '#3b82f6',
    linkSpacing: 'normal',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'pink-paradise',
    name: 'Paradis rose',
    category: 'gradient',
    tags: ['rose', 'violet', 'paradis', 'doux'],
    theme: 'gradient',
    accentColor: '#ec4899',
    titleColor: '#ffffff',
    bioColor: '#fce7f3',
    linkColor: '#ffffff',
    fontFamily: 'poppins',
    buttonShape: 'rounded-full',
    buttonVariant: 'shadow',
    avatarShape: 'circle',
    gradientFrom: '#ec4899',
    gradientTo: '#a855f7',
    linkSpacing: 'airy',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'deep-space',
    name: 'Espace profond',
    category: 'gradient',
    tags: ['bleu', 'noir', 'espace', 'galaxie'],
    theme: 'gradient',
    accentColor: '#6366f1',
    titleColor: '#ffffff',
    bioColor: '#c7d2fe',
    linkColor: '#ffffff',
    fontFamily: 'space-grotesk',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: '#1e1b4b',
    gradientTo: '#0f172a',
    linkSpacing: 'normal',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'tropical-sunset',
    name: 'Coucher tropical',
    category: 'gradient',
    tags: ['rouge', 'orange', 'tropical', 'feu'],
    theme: 'gradient',
    accentColor: '#ef4444',
    titleColor: '#ffffff',
    bioColor: '#fecaca',
    linkColor: '#ffffff',
    fontFamily: 'dm-sans',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#ef4444',
    gradientTo: '#eab308',
    linkSpacing: 'normal',
    hoverAnimation: 'slide',
    headerStyle: 'classic',
  },
  {
    id: 'ocean-gradient',
    name: 'Océan dégradé',
    category: 'gradient',
    tags: ['bleu', 'turquoise', 'mer', 'profond'],
    theme: 'gradient',
    accentColor: '#0891b2',
    titleColor: '#ffffff',
    bioColor: '#a5f3fc',
    linkColor: '#ffffff',
    fontFamily: 'outfit',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#155e75',
    gradientTo: '#0d9488',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  // ── Template Card (carte glassmorphism) ─────────────────────────────────
  {
    id: 'aurora-card',
    name: 'Aurore carte',
    category: 'gradient',
    tags: ['carte', 'glassmorphism', 'aurore', 'gradient', 'flottante'],
    theme: 'gradient',
    accentColor: '#06b6d4',
    titleColor: '#ffffff',
    bioColor: '#a5f3fc',
    linkColor: '#ffffff',
    fontFamily: 'poppins',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#7c3aed',
    gradientTo: '#06b6d4',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'card',
  },
]
