/**
 * @file modules/biolink/templates/presets/luxury.ts
 * @module biolink
 * @description Templates de la catégorie "Luxe".
 *   Élégance, raffinement, polices serif et couleurs précieuses.
 */

import type { BioTemplate } from '../types'

/** 9 templates luxe (7 classic + 1 minimal + 1 card) */
export const LUXURY_TEMPLATES: BioTemplate[] = [
  {
    id: 'black-gold',
    name: 'Noir et or',
    category: 'luxury',
    tags: ['noir', 'or', 'chic', 'élégant'],
    theme: 'dark',
    accentColor: '#d97706',
    titleColor: '#fbbf24',
    bioColor: '#f59e0b',
    linkColor: '#18181b',
    fontFamily: 'playfair',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'airy',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'marble-elite',
    name: 'Marbre élite',
    category: 'luxury',
    tags: ['blanc', 'marbre', 'pur', 'premium'],
    theme: 'minimal',
    accentColor: '#78716c',
    titleColor: '#1c1917',
    bioColor: '#57534e',
    linkColor: '#ffffff',
    fontFamily: 'playfair',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'airy',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'champagne',
    name: 'Champagne',
    category: 'luxury',
    tags: ['doré', 'champagne', 'fête', 'luxe'],
    theme: 'default',
    accentColor: '#ca8a04',
    titleColor: '#713f12',
    bioColor: '#854d0e',
    linkColor: '#ffffff',
    fontFamily: 'lora',
    buttonShape: 'rounded-full',
    buttonVariant: 'shadow',
    avatarShape: 'circle',
    gradientFrom: '#fef3c7',
    gradientTo: '#fffbeb',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'velvet-night',
    name: 'Nuit de velours',
    category: 'luxury',
    tags: ['violet', 'velours', 'nuit', 'royal'],
    theme: 'dark',
    accentColor: '#a855f7',
    titleColor: '#d8b4fe',
    bioColor: '#c084fc',
    linkColor: '#ffffff',
    fontFamily: 'playfair',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#2e1065',
    gradientTo: '#1e1b4b',
    linkSpacing: 'airy',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'rose-gold',
    name: 'Or rose',
    category: 'luxury',
    tags: ['rose', 'or', 'doré', 'féminin'],
    theme: 'default',
    accentColor: '#e11d48',
    titleColor: '#881337',
    bioColor: '#9f1239',
    linkColor: '#ffffff',
    fontFamily: 'playfair',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#fff1f2',
    gradientTo: '#fef2f2',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'ivory-tower',
    name: 'Tour d\'ivoire',
    category: 'luxury',
    tags: ['ivoire', 'crème', 'raffiné', 'classique'],
    theme: 'minimal',
    accentColor: '#a16207',
    titleColor: '#422006',
    bioColor: '#713f12',
    linkColor: '#422006',
    fontFamily: 'lora',
    buttonShape: 'rounded-lg',
    buttonVariant: 'outline',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'airy',
    hoverAnimation: 'none',
    headerStyle: 'classic',
  },
  {
    id: 'platinum',
    name: 'Platine',
    category: 'luxury',
    tags: ['argent', 'gris', 'métallique', 'chic'],
    theme: 'dark',
    accentColor: '#94a3b8',
    titleColor: '#e2e8f0',
    bioColor: '#cbd5e1',
    linkColor: '#0f172a',
    fontFamily: 'inter',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  // ── Template Minimal (layout texte-first) ───────────────────────────────
  {
    id: 'ivory-minimal',
    name: 'Ivoire minimal',
    category: 'luxury',
    tags: ['ivoire', 'doré', 'minimal-layout', 'aéré', 'sans-avatar'],
    theme: 'default',
    accentColor: '#b45309',
    titleColor: '#78350f',
    bioColor: '#a8a29e',
    linkColor: '#78350f',
    fontFamily: 'lora',
    buttonShape: 'rounded-lg',
    buttonVariant: 'outline',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'airy',
    hoverAnimation: 'none',
    headerStyle: 'minimal',
  },
  // ── Template Card (carte glassmorphism) ─────────────────────────────────
  {
    id: 'crystal-card',
    name: 'Cristal carte',
    category: 'luxury',
    tags: ['carte', 'glassmorphism', 'cristal', 'élégant', 'ombre'],
    theme: 'dark',
    accentColor: '#d4d4d8',
    titleColor: '#fafafa',
    bioColor: '#a1a1aa',
    linkColor: '#fafafa',
    fontFamily: 'playfair',
    buttonShape: 'rounded-lg',
    buttonVariant: 'shadow',
    avatarShape: 'rounded-square',
    gradientFrom: '#18181b',
    gradientTo: '#27272a',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'card',
  },
]
