/**
 * @file modules/biolink/templates/presets/minimal.ts
 * @module biolink
 * @description Templates de la catégorie "Minimaliste".
 *   Designs épurés, sobres, avec peu de couleurs et des espaces aérés.
 */

import type { BioTemplate } from '../types'

/** 8 templates minimalistes (7 classic + 1 minimal layout) */
export const MINIMAL_TEMPLATES: BioTemplate[] = [
  {
    id: 'clean-slate',
    name: 'Ardoise propre',
    category: 'minimal',
    tags: ['blanc', 'épuré', 'simple', 'clair'],
    theme: 'default',
    accentColor: '#6366f1',
    titleColor: '#111827',
    bioColor: '#6b7280',
    linkColor: null,
    fontFamily: 'inter',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'paper-cut',
    name: 'Papier découpé',
    category: 'minimal',
    tags: ['pierre', 'sérif', 'élégant', 'contour'],
    theme: 'default',
    accentColor: '#78716c',
    titleColor: '#292524',
    bioColor: '#78716c',
    linkColor: '#292524',
    fontFamily: 'lora',
    buttonShape: 'rounded-lg',
    buttonVariant: 'outline',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'airy',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'swiss-grid',
    name: 'Grille suisse',
    category: 'minimal',
    tags: ['noir', 'blanc', 'typo', 'graphique'],
    theme: 'default',
    accentColor: '#18181b',
    titleColor: '#18181b',
    bioColor: '#71717a',
    linkColor: '#ffffff',
    fontFamily: 'space-grotesk',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'compact',
    hoverAnimation: 'none',
    headerStyle: 'classic',
  },
  {
    id: 'soft-cloud',
    name: 'Nuage doux',
    category: 'minimal',
    tags: ['doux', 'arrondi', 'léger', 'blanc'],
    theme: 'default',
    accentColor: '#a5b4fc',
    titleColor: '#312e81',
    bioColor: '#6366f1',
    linkColor: null,
    fontFamily: 'dm-sans',
    buttonShape: 'rounded-full',
    buttonVariant: 'shadow',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'airy',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'zen-garden',
    name: 'Jardin zen',
    category: 'minimal',
    tags: ['calme', 'neutre', 'zen', 'sable'],
    theme: 'minimal',
    accentColor: '#92400e',
    titleColor: '#451a03',
    bioColor: '#78716c',
    linkColor: '#451a03',
    fontFamily: 'lora',
    buttonShape: 'rounded-lg',
    buttonVariant: 'outline',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'airy',
    hoverAnimation: 'none',
    headerStyle: 'classic',
  },
  {
    id: 'mono-type',
    name: 'Monotype',
    category: 'minimal',
    tags: ['monospace', 'texte', 'code', 'simple'],
    theme: 'default',
    accentColor: '#374151',
    titleColor: '#111827',
    bioColor: '#6b7280',
    linkColor: '#ffffff',
    fontFamily: 'space-grotesk',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'compact',
    hoverAnimation: 'none',
    headerStyle: 'classic',
  },
  {
    id: 'whisper',
    name: 'Murmure',
    category: 'minimal',
    tags: ['subtil', 'léger', 'discret', 'doux'],
    theme: 'minimal',
    accentColor: '#d1d5db',
    titleColor: '#374151',
    bioColor: '#9ca3af',
    linkColor: '#374151',
    fontFamily: 'outfit',
    buttonShape: 'rounded-full',
    buttonVariant: 'outline',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  // ── Template Minimal (layout texte-first) ───────────────────────────────
  {
    id: 'ultra-clean',
    name: 'Ultra épuré',
    category: 'minimal',
    tags: ['épuré', 'texte', 'minimal-layout', 'sans-avatar', 'outline'],
    theme: 'default',
    accentColor: '#6366f1',
    titleColor: '#111827',
    bioColor: '#9ca3af',
    linkColor: null,
    fontFamily: 'inter',
    buttonShape: 'rounded-lg',
    buttonVariant: 'outline',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'minimal',
  },
]
