/**
 * @file modules/biolink/templates/presets/music.ts
 * @module biolink
 * @description Templates de la catégorie "Musique".
 *   Univers musical, artistique, inspirations vinyle, concert et studio.
 */

import type { BioTemplate } from '../types'

/** 7 templates musique */
export const MUSIC_TEMPLATES: BioTemplate[] = [
  {
    id: 'vinyl-night',
    name: 'Nuit vinyle',
    category: 'music',
    tags: ['violet', 'sombre', 'vinyle', 'nocturne'],
    theme: 'dark',
    accentColor: '#7c3aed',
    titleColor: '#c4b5fd',
    bioColor: '#a78bfa',
    linkColor: '#ffffff',
    fontFamily: 'playfair',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'spotify-green',
    name: 'Vert Spotify',
    category: 'music',
    tags: ['vert', 'spotify', 'stream', 'audio'],
    theme: 'dark',
    accentColor: '#1db954',
    titleColor: '#4ade80',
    bioColor: '#86efac',
    linkColor: '#ffffff',
    fontFamily: 'dm-sans',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'neon-stage',
    name: 'Scène néon',
    category: 'music',
    tags: ['rose', 'néon', 'concert', 'scène'],
    theme: 'neon',
    accentColor: '#ec4899',
    titleColor: '#f9a8d4',
    bioColor: '#f472b6',
    linkColor: '#ffffff',
    fontFamily: 'bebas-neue',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'jazz-club',
    name: 'Club de jazz',
    category: 'music',
    tags: ['doré', 'sombre', 'jazz', 'élégant'],
    theme: 'dark',
    accentColor: '#d97706',
    titleColor: '#fcd34d',
    bioColor: '#fbbf24',
    linkColor: '#18181b',
    fontFamily: 'playfair',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#1c1917',
    gradientTo: '#292524',
    linkSpacing: 'airy',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'electric-beat',
    name: 'Beat électrique',
    category: 'music',
    tags: ['cyan', 'électro', 'beat', 'edm'],
    theme: 'neon',
    accentColor: '#06b6d4',
    titleColor: '#22d3ee',
    bioColor: '#67e8f9',
    linkColor: '#ffffff',
    fontFamily: 'space-grotesk',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: '#0e7490',
    gradientTo: '#7c3aed',
    linkSpacing: 'compact',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'acoustic-wood',
    name: 'Bois acoustique',
    category: 'music',
    tags: ['marron', 'bois', 'acoustique', 'folk'],
    theme: 'default',
    accentColor: '#92400e',
    titleColor: '#451a03',
    bioColor: '#78350f',
    linkColor: '#ffffff',
    fontFamily: 'lora',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'hip-hop',
    name: 'Hip-hop',
    category: 'music',
    tags: ['rouge', 'noir', 'rap', 'urban'],
    theme: 'dark',
    accentColor: '#ef4444',
    titleColor: '#fca5a5',
    bioColor: '#f87171',
    linkColor: '#ffffff',
    fontFamily: 'bebas-neue',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'compact',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
]
