/**
 * @file modules/biolink/templates/presets/nature.ts
 * @module biolink
 * @description Templates de la catégorie "Nature".
 *   Couleurs naturelles, organiques, inspirées de la terre et des paysages.
 */

import type { BioTemplate } from '../types'

/** 8 templates nature (7 classic + 1 hero) */
export const NATURE_TEMPLATES: BioTemplate[] = [
  {
    id: 'forest-moss',
    name: 'Mousse forestière',
    category: 'nature',
    tags: ['vert', 'forêt', 'mousse', 'bois'],
    theme: 'default',
    accentColor: '#15803d',
    titleColor: '#14532d',
    bioColor: '#166534',
    linkColor: '#ffffff',
    fontFamily: 'lora',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'airy',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'ocean-breeze',
    name: 'Brise océane',
    category: 'nature',
    tags: ['bleu', 'mer', 'brise', 'aqua'],
    theme: 'default',
    accentColor: '#0284c7',
    titleColor: '#0c4a6e',
    bioColor: '#0369a1',
    linkColor: '#ffffff',
    fontFamily: 'dm-sans',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'slide',
    headerStyle: 'classic',
  },
  {
    id: 'lavender-field',
    name: 'Champ de lavande',
    category: 'nature',
    tags: ['mauve', 'lavande', 'violet', 'provence'],
    theme: 'default',
    accentColor: '#9333ea',
    titleColor: '#581c87',
    bioColor: '#7e22ce',
    linkColor: '#ffffff',
    fontFamily: 'poppins',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'airy',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'autumn-leaves',
    name: 'Feuilles d\'automne',
    category: 'nature',
    tags: ['orange', 'automne', 'chaud', 'feuille'],
    theme: 'default',
    accentColor: '#c2410c',
    titleColor: '#7c2d12',
    bioColor: '#9a3412',
    linkColor: '#ffffff',
    fontFamily: 'lora',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'tropical-palm',
    name: 'Palmier tropical',
    category: 'nature',
    tags: ['vert', 'tropical', 'palmier', 'exotique'],
    theme: 'default',
    accentColor: '#16a34a',
    titleColor: '#052e16',
    bioColor: '#15803d',
    linkColor: '#ffffff',
    fontFamily: 'poppins',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#15803d',
    gradientTo: '#0d9488',
    linkSpacing: 'normal',
    hoverAnimation: 'slide',
    headerStyle: 'classic',
  },
  {
    id: 'desert-sand',
    name: 'Sable du désert',
    category: 'nature',
    tags: ['sable', 'désert', 'beige', 'chaud'],
    theme: 'minimal',
    accentColor: '#b45309',
    titleColor: '#78350f',
    bioColor: '#92400e',
    linkColor: '#78350f',
    fontFamily: 'lora',
    buttonShape: 'rounded-lg',
    buttonVariant: 'outline',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'airy',
    hoverAnimation: 'none',
    headerStyle: 'classic',
  },
  {
    id: 'cherry-blossom',
    name: 'Fleur de cerisier',
    category: 'nature',
    tags: ['rose', 'cerisier', 'japon', 'printemps'],
    theme: 'default',
    accentColor: '#ec4899',
    titleColor: '#831843',
    bioColor: '#9d174d',
    linkColor: '#ffffff',
    fontFamily: 'playfair',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#fce7f3',
    gradientTo: '#fdf2f8',
    linkSpacing: 'airy',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  // ── Template Hero ───────────────────────────────────────────────────────
  {
    id: 'forest-hero',
    name: 'Forêt hero',
    category: 'nature',
    tags: ['vert', 'forêt', 'hero', 'immersif', 'plein-écran'],
    theme: 'dark',
    accentColor: '#166534',
    titleColor: '#ffffff',
    bioColor: '#bbf7d0',
    linkColor: '#ffffff',
    fontFamily: 'lora',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#14532d',
    gradientTo: '#052e16',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'hero',
  },
]
