/**
 * @file modules/biolink/templates/presets/pastel.ts
 * @module biolink
 * @description Templates de la catégorie "Pastel".
 *   Tons doux, apaisants, couleurs atténuées et atmosphère légère.
 */

import type { BioTemplate } from '../types'

/** 8 templates pastel (7 classic + 1 card) */
export const PASTEL_TEMPLATES: BioTemplate[] = [
  {
    id: 'bubblegum',
    name: 'Bubblegum',
    category: 'pastel',
    tags: ['rose', 'bonbon', 'doux', 'fun'],
    theme: 'default',
    accentColor: '#f9a8d4',
    titleColor: '#831843',
    bioColor: '#9d174d',
    linkColor: '#831843',
    fontFamily: 'poppins',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#fce7f3',
    gradientTo: '#fff1f2',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'mint-fresh',
    name: 'Menthe fraîche',
    category: 'pastel',
    tags: ['vert', 'menthe', 'frais', 'doux'],
    theme: 'default',
    accentColor: '#6ee7b7',
    titleColor: '#064e3b',
    bioColor: '#047857',
    linkColor: '#064e3b',
    fontFamily: 'outfit',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#d1fae5',
    gradientTo: '#ecfdf5',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'lilac-dream',
    name: 'Rêve lilas',
    category: 'pastel',
    tags: ['violet', 'lilas', 'rêve', 'doux'],
    theme: 'default',
    accentColor: '#c4b5fd',
    titleColor: '#4c1d95',
    bioColor: '#5b21b6',
    linkColor: '#4c1d95',
    fontFamily: 'playfair',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#ede9fe',
    gradientTo: '#f5f3ff',
    linkSpacing: 'airy',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'peach-cream',
    name: 'Crème pêche',
    category: 'pastel',
    tags: ['pêche', 'crème', 'chaud', 'doux'],
    theme: 'default',
    accentColor: '#fdba74',
    titleColor: '#7c2d12',
    bioColor: '#9a3412',
    linkColor: '#7c2d12',
    fontFamily: 'dm-sans',
    buttonShape: 'rounded-full',
    buttonVariant: 'shadow',
    avatarShape: 'circle',
    gradientFrom: '#fff7ed',
    gradientTo: '#fffbeb',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'sky-blue',
    name: 'Bleu ciel',
    category: 'pastel',
    tags: ['bleu', 'ciel', 'doux', 'clair'],
    theme: 'default',
    accentColor: '#7dd3fc',
    titleColor: '#0c4a6e',
    bioColor: '#0369a1',
    linkColor: '#0c4a6e',
    fontFamily: 'outfit',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#e0f2fe',
    gradientTo: '#f0f9ff',
    linkSpacing: 'normal',
    hoverAnimation: 'slide',
    headerStyle: 'classic',
  },
  {
    id: 'cotton-candy',
    name: 'Barbe à papa',
    category: 'pastel',
    tags: ['rose', 'bleu', 'bonbon', 'multicolore'],
    theme: 'default',
    accentColor: '#f0abfc',
    titleColor: '#701a75',
    bioColor: '#86198f',
    linkColor: '#701a75',
    fontFamily: 'poppins',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#fae8ff',
    gradientTo: '#e0f2fe',
    linkSpacing: 'airy',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'lemon-sorbet',
    name: 'Sorbet citron',
    category: 'pastel',
    tags: ['jaune', 'citron', 'frais', 'été'],
    theme: 'default',
    accentColor: '#fde047',
    titleColor: '#713f12',
    bioColor: '#854d0e',
    linkColor: '#713f12',
    fontFamily: 'outfit',
    buttonShape: 'rounded-lg',
    buttonVariant: 'shadow',
    avatarShape: 'rounded-square',
    gradientFrom: '#fef9c3',
    gradientTo: '#fefce8',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  // ── Template Card (carte glassmorphism) ─────────────────────────────────
  {
    id: 'frosted-card',
    name: 'Givre carte',
    category: 'pastel',
    tags: ['carte', 'glassmorphism', 'pastel', 'givre', 'pill'],
    theme: 'default',
    accentColor: '#a78bfa',
    titleColor: '#312e81',
    bioColor: '#6366f1',
    linkColor: null,
    fontFamily: 'dm-sans',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#e0e7ff',
    gradientTo: '#fce7f3',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'card',
  },
]
