/**
 * @file modules/biolink/templates/presets/retro.ts
 * @module biolink
 * @description Templates de la catégorie "Rétro".
 *   Inspirations vintage, nostalgiques, pixel art et vaporwave.
 */

import type { BioTemplate } from '../types'

/** 7 templates rétro */
export const RETRO_TEMPLATES: BioTemplate[] = [
  {
    id: 'vintage-paper',
    name: 'Papier vintage',
    category: 'retro',
    tags: ['sépia', 'vieux', 'papier', 'classique'],
    theme: 'minimal',
    accentColor: '#92400e',
    titleColor: '#451a03',
    bioColor: '#78350f',
    linkColor: '#451a03',
    fontFamily: 'playfair',
    buttonShape: 'rounded-lg',
    buttonVariant: 'outline',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'airy',
    hoverAnimation: 'none',
    headerStyle: 'classic',
  },
  {
    id: 'vaporwave',
    name: 'Vaporwave',
    category: 'retro',
    tags: ['rose', 'violet', 'néon', '80s'],
    theme: 'gradient',
    accentColor: '#e879f9',
    titleColor: '#ffffff',
    bioColor: '#f0abfc',
    linkColor: '#ffffff',
    fontFamily: 'bebas-neue',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: '#d946ef',
    gradientTo: '#6366f1',
    linkSpacing: 'compact',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'pixel-arcade',
    name: 'Pixel arcade',
    category: 'retro',
    tags: ['vert', 'néon', 'pixel', 'jeu'],
    theme: 'dark',
    accentColor: '#22c55e',
    titleColor: '#4ade80',
    bioColor: '#86efac',
    linkColor: '#052e16',
    fontFamily: 'space-grotesk',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'compact',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'vinyl-groove',
    name: 'Groove vinyle',
    category: 'retro',
    tags: ['marron', 'vinyle', 'musique', '70s'],
    theme: 'default',
    accentColor: '#a16207',
    titleColor: '#713f12',
    bioColor: '#854d0e',
    linkColor: '#ffffff',
    fontFamily: 'playfair',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'neon-80s',
    name: 'Néon 80\'s',
    category: 'retro',
    tags: ['néon', 'rose', 'bleu', '80s'],
    theme: 'neon',
    accentColor: '#f472b6',
    titleColor: '#f9a8d4',
    bioColor: '#f0abfc',
    linkColor: '#ffffff',
    fontFamily: 'bebas-neue',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'polaroid',
    name: 'Polaroid',
    category: 'retro',
    tags: ['blanc', 'cadre', 'photo', 'vintage'],
    theme: 'default',
    accentColor: '#0891b2',
    titleColor: '#1e3a5f',
    bioColor: '#475569',
    linkColor: '#ffffff',
    fontFamily: 'lora',
    buttonShape: 'rounded-lg',
    buttonVariant: 'shadow',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'cassette-tape',
    name: 'Cassette audio',
    category: 'retro',
    tags: ['orange', 'marron', 'cassette', '90s'],
    theme: 'dark',
    accentColor: '#f97316',
    titleColor: '#fdba74',
    bioColor: '#fb923c',
    linkColor: '#ffffff',
    fontFamily: 'space-grotesk',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'slide',
    headerStyle: 'classic',
  },
]
