/**
 * @file modules/biolink/templates/presets/sport.ts
 * @module biolink
 * @description Templates de la catégorie "Sport".
 *   Énergie, performance, couleurs dynamiques et vibrantes.
 */

import type { BioTemplate } from '../types'

/** 8 templates sport (7 classic + 1 banner) */
export const SPORT_TEMPLATES: BioTemplate[] = [
  {
    id: 'energy-rush',
    name: 'Énergie pure',
    category: 'sport',
    tags: ['rouge', 'orange', 'énergie', 'dynamique'],
    theme: 'gradient',
    accentColor: '#ef4444',
    titleColor: '#ffffff',
    bioColor: '#fecaca',
    linkColor: '#ffffff',
    fontFamily: 'bebas-neue',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: '#dc2626',
    gradientTo: '#f97316',
    linkSpacing: 'compact',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'ice-arena',
    name: 'Arène de glace',
    category: 'sport',
    tags: ['bleu', 'glacé', 'froid', 'hockey'],
    theme: 'dark',
    accentColor: '#0ea5e9',
    titleColor: '#7dd3fc',
    bioColor: '#38bdf8',
    linkColor: '#ffffff',
    fontFamily: 'dm-sans',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: '#0c4a6e',
    gradientTo: '#0f172a',
    linkSpacing: 'normal',
    hoverAnimation: 'slide',
    headerStyle: 'classic',
  },
  {
    id: 'champion-gold',
    name: 'Champion d\'or',
    category: 'sport',
    tags: ['or', 'noir', 'champion', 'victoire'],
    theme: 'dark',
    accentColor: '#eab308',
    titleColor: '#fef08a',
    bioColor: '#facc15',
    linkColor: '#18181b',
    fontFamily: 'bebas-neue',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'compact',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'grass-field',
    name: 'Terrain de foot',
    category: 'sport',
    tags: ['vert', 'foot', 'terrain', 'pelouse'],
    theme: 'default',
    accentColor: '#16a34a',
    titleColor: '#14532d',
    bioColor: '#166534',
    linkColor: '#ffffff',
    fontFamily: 'dm-sans',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#dcfce7',
    gradientTo: '#f0fdf4',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'midnight-run',
    name: 'Course nocturne',
    category: 'sport',
    tags: ['noir', 'néon', 'course', 'running'],
    theme: 'dark',
    accentColor: '#06b6d4',
    titleColor: '#22d3ee',
    bioColor: '#67e8f9',
    linkColor: '#ffffff',
    fontFamily: 'poppins',
    buttonShape: 'rounded-full',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'slide',
    headerStyle: 'classic',
  },
  {
    id: 'boxing-ring',
    name: 'Ring de boxe',
    category: 'sport',
    tags: ['rouge', 'noir', 'boxe', 'combat'],
    theme: 'dark',
    accentColor: '#dc2626',
    titleColor: '#fca5a5',
    bioColor: '#f87171',
    linkColor: '#ffffff',
    fontFamily: 'bebas-neue',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: '#7f1d1d',
    gradientTo: '#18181b',
    linkSpacing: 'compact',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'team-spirit',
    name: 'Esprit d\'équipe',
    category: 'sport',
    tags: ['bleu', 'rouge', 'équipe', 'collectif'],
    theme: 'default',
    accentColor: '#2563eb',
    titleColor: '#1e40af',
    bioColor: '#3b82f6',
    linkColor: '#ffffff',
    fontFamily: 'poppins',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  // ── Template Banner ─────────────────────────────────────────────────────
  {
    id: 'stadium-banner',
    name: 'Stade bannière',
    category: 'sport',
    tags: ['bannière', 'stade', 'dynamique', 'énergie'],
    theme: 'dark',
    accentColor: '#ef4444',
    titleColor: '#ffffff',
    bioColor: '#fca5a5',
    linkColor: '#ffffff',
    fontFamily: 'bebas-neue',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#18181b',
    gradientTo: '#1f2937',
    linkSpacing: 'compact',
    hoverAnimation: 'slide',
    headerStyle: 'banner',
  },
]
