/**
 * @file modules/biolink/templates/presets/tech.ts
 * @module biolink
 * @description Templates de la catégorie "Tech".
 *   Inspirations développeur, terminal, IDE et blueprints.
 */

import type { BioTemplate } from '../types'

/** 8 templates tech (7 classic + 1 minimal layout) */
export const TECH_TEMPLATES: BioTemplate[] = [
  {
    id: 'terminal-green',
    name: 'Terminal vert',
    category: 'tech',
    tags: ['vert', 'terminal', 'hacker', 'code'],
    theme: 'dark',
    accentColor: '#22c55e',
    titleColor: '#4ade80',
    bioColor: '#86efac',
    linkColor: '#052e16',
    fontFamily: 'space-grotesk',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'compact',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    category: 'tech',
    tags: ['bleu', 'plan', 'technique', 'schéma'],
    theme: 'dark',
    accentColor: '#3b82f6',
    titleColor: '#93c5fd',
    bioColor: '#60a5fa',
    linkColor: '#ffffff',
    fontFamily: 'space-grotesk',
    buttonShape: 'rounded-lg',
    buttonVariant: 'outline',
    avatarShape: 'rounded-square',
    gradientFrom: '#1e3a5f',
    gradientTo: '#172554',
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'dark-ide',
    name: 'IDE sombre',
    category: 'tech',
    tags: ['sombre', 'cyan', 'ide', 'éditeur'],
    theme: 'dark',
    accentColor: '#06b6d4',
    titleColor: '#67e8f9',
    bioColor: '#22d3ee',
    linkColor: '#ffffff',
    fontFamily: 'space-grotesk',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'rounded-square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'compact',
    hoverAnimation: 'none',
    headerStyle: 'classic',
  },
  {
    id: 'matrix-rain',
    name: 'Pluie matricielle',
    category: 'tech',
    tags: ['vert', 'matrix', 'digital', 'code'],
    theme: 'dark',
    accentColor: '#16a34a',
    titleColor: '#22c55e',
    bioColor: '#4ade80',
    linkColor: '#052e16',
    fontFamily: 'space-grotesk',
    buttonShape: 'rounded-none',
    buttonVariant: 'filled',
    avatarShape: 'square',
    gradientFrom: '#022c22',
    gradientTo: '#0a0a0a',
    linkSpacing: 'compact',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'silicon-valley',
    name: 'Silicon Valley',
    category: 'tech',
    tags: ['bleu', 'startup', 'clean', 'moderne'],
    theme: 'default',
    accentColor: '#2563eb',
    titleColor: '#1e40af',
    bioColor: '#3b82f6',
    linkColor: '#ffffff',
    fontFamily: 'inter',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'normal',
    hoverAnimation: 'scale',
    headerStyle: 'classic',
  },
  {
    id: 'circuit-board',
    name: 'Circuit imprimé',
    category: 'tech',
    tags: ['vert', 'circuit', 'hardware', 'pcb'],
    theme: 'dark',
    accentColor: '#059669',
    titleColor: '#34d399',
    bioColor: '#6ee7b7',
    linkColor: '#ffffff',
    fontFamily: 'space-grotesk',
    buttonShape: 'rounded-none',
    buttonVariant: 'outline',
    avatarShape: 'square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'compact',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  {
    id: 'ai-neural',
    name: 'IA neuronale',
    category: 'tech',
    tags: ['violet', 'ia', 'neural', 'futuriste'],
    theme: 'dark',
    accentColor: '#8b5cf6',
    titleColor: '#c4b5fd',
    bioColor: '#a78bfa',
    linkColor: '#ffffff',
    fontFamily: 'dm-sans',
    buttonShape: 'rounded-lg',
    buttonVariant: 'filled',
    avatarShape: 'circle',
    gradientFrom: '#1e1b4b',
    gradientTo: '#0c0a09',
    linkSpacing: 'normal',
    hoverAnimation: 'glow',
    headerStyle: 'classic',
  },
  // ── Template Minimal (layout texte-first) ───────────────────────────────
  {
    id: 'dev-portfolio',
    name: 'Portfolio dev',
    category: 'tech',
    tags: ['minimal-layout', 'portfolio', 'développeur', 'compact', 'sans-avatar'],
    theme: 'dark',
    accentColor: '#22d3ee',
    titleColor: '#e2e8f0',
    bioColor: '#94a3b8',
    linkColor: '#22d3ee',
    fontFamily: 'space-grotesk',
    buttonShape: 'rounded-none',
    buttonVariant: 'outline',
    avatarShape: 'square',
    gradientFrom: null,
    gradientTo: null,
    linkSpacing: 'compact',
    hoverAnimation: 'none',
    headerStyle: 'minimal',
  },
]
